### PR TITLE
fix: point belong arc 2d

### PR DESCRIPTION
**Pull request by Launayl**
* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:
Error in point_belongs in arc2d , the detection of trigo or clockwise directions doesn't work

### CODE REVIEW

**Comment by sbendjebla** [comment]
@WirajanDASILVA

**Comment by AxelRinghausen** [comment]
Be careful, this might interfere with https://github.com/Dessia-tech/volmdlr/pull/478.

**Comment by AxelRinghausen** [comment]
Merging into `master` on purpose ?

**Comment by Launayl** [comment]
Yes! It's because I have this issue when I run one of my test script of Power Transmission (In Drone). So now , it's not possible to merge pull request , I can put a temporary restriction into the setup for the volmdlr version  but with  the change of rotation /rotation_inplace it's not convenient. If it's not possible to merge in master, I think I can change directly the module powertransmission to use an other methods

**Review by masfaraud — APPROVED** [review]

**Pull request merged**
