### PR TITLE
Fix LineSegment3D linesegment_intersections method

### LINKED ISSUE #380: Bug: Line_Segement3D.linesegment_intersection()
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
Line_Segement3D.linesegment_intersection() returning bad results 
image

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

`
face_contour_points_pairs = [(vm.Point3D(-0.5, -0.5, 0.5), vm.Point3D(0.5, -0.5, 0.5)), (vm.Point3D(0.5, -0.5, 0.5), vm.Point3D(0.5, 0.5, 0.5)), (vm.Point3D(0.5, 0.5, 0.5), vm.Point3D(-0.5, 0.5, 0.5)), (vm.Point3D(-0.5, 0.5, 0.5), vm.Point3D(-0.5, -0.5, 0.5))]
contour = vm.wires.Contour3D([vm.edges.LineSegment3D(start, end) for start, end in face_contour_points_pairs])
edge = vm.edges.LineSegment3D(vm.Point3D(-0.5, 0.5, 1.5), vm.Point3D(0.5, 0.5, 1.5))
intersections = []
ax=contour.plot()
edge.plot(ax=ax, color='r')
for prim in contour.primitives:
    intersection = prim.linesegment_intersection(edge)
    if intersection:
        intersection.plot(ax, color='b')
`

* **What is the expected behavior?**
no intersection should be returned in the use case

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  
  - python version: 3.9

### PR DESCRIPTION
**Pull request by WirajanDASILVA**
* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:
closes #380

### CODE REVIEW

**Review by sbendjebla — COMMENTED** [review]
Actually, I think that the problem comes from: `intersection = self.intersection(linesegment)`, which should return `None` instead of a valid `Point3D` (for your issue #380 example)
If we correct `intersection` method, we can keep this line (is it quicker than `point_belongs` !?):
```
if intersection in [self.start, self.end, linesegment.start, linesegment.end]:
       return intersection
```

**Comment by WirajanDASILVA** [comment]
> Actually, I think that the problem comes from: `intersection = self.intersection(linesegment)`, which should return `None` instead of a valid `Point3D` (for your issue #380 example) If we correct `intersection` method, we can keep this line (is it quicker than `point_belongs` !?):
> 
> ```
> if intersection in [self.start, self.end, linesegment.start, linesegment.end]:
>        return intersection
> ```

oui, en faite j'ai essayé de corriger self.intersection, ça été plus complexe que ce je pensais. Ça na pas marché. c que j'ai ait pourrait être un quick fix, effectivement il faudrait regarder la méthode intersection. Mais de toute façon, les lignes supprimés sont en effet inutiles, puisque point_belongs comprends déjà le start et end

**Comment by sbendjebla** [comment]
> > Actually, I think that the problem comes from: `intersection = self.intersection(linesegment)`, which should return `None` instead of a valid `Point3D` (for your issue #380 example) If we correct `intersection` method, we can keep this line (is it quicker than `point_belongs` !?):
> > ```
> > if intersection in [self.start, self.end, linesegment.start, linesegment.end]:
> >        return intersection
> > ```
> 
> oui, en faite j'ai essayé de corriger self.intersection, ça été plus complexe que ce je pensais. Ça na pas marché. Ce que j'ai fait pourrait être un quick fix, effectivement il faudrait regarder la méthode intersection. Mais de toute façon, les lignes supprimés sont en effet inutiles, puisque point_belongs comprends déjà le start et end

**Comment by WirajanDASILVA** [comment]
> > > Actually, I think that the problem comes from: `intersection = self.intersection(linesegment)`, which should return `None` instead of a valid `Point3D` (for your issue #380 example) If we correct `intersection` method, we can keep this line (is it quicker than `point_belongs` !?):
> > > ```
> > > if intersection in [self.start, self.end, linesegment.start, linesegment.end]:
> > >        return intersection
> > > ```
> > 
> > 
> > oui, en faite j'ai essayé de corriger self.intersection, ça été plus complexe que ce je pensais. Ça na pas marché. Ce que j'ai fait pourrait être un quick fix, effectivement il faudrait regarder la méthode intersection. Mais de toute façon, les lignes supprimés sont en effet inutiles, puisque point_belongs comprends déjà le start et end
> 
> Yes, it can be accepted as a quick fix ! We should create a new **Issue** for **LineSegment3D.intersection()** Furthermore, I proposed to use`intersection in [self.start, self.end, linesegment.start, linesegment.end]`to check before using `point_belongs` because it is quicker (I think) !

Sorry, for using French in my last reply, didn't realise it. Yes, I believe there is no problem once intersection is fixed, we can use it.

**Review by sbendjebla — APPROVED** [review]

**Pull request merged**
