### PR TITLE
Reference Path

### PR DESCRIPTION
**Pull request by GhislainJ**
* **Please check if the PR fulfills these requirements**
- [x] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [x] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

It probably lacks a lot of cases, but I still wanted to submit this early.
Note : I wrongly pushed another dev (schemas) that I'll cherry-pick on another branch

### CODE REVIEW

**Comment by GabrielJMS** [comment]
Why can't we be more generic and create an intermediate python object "Forms" and delegate the interaction between python objects and the Front-end to it?

I believe this change adds overhead to volmdlr definitions losing its genericity and potentially reducing community adoption.

**Comment by GabrielJMS** [comment]
Why can't we be more generic and create an intermediate python object "Forms" and delegate the interaction between python objects and the Front-end to it?

I believe this change adds overhead to the volmdlr definitions losing its genericity and potentially reduce community adoption.

**Comment by GhislainJ** [comment]
@GabrielJMS

As much as I agree with your point, it seems that there is no real other simple way of inject these `reference_path` into JSONs than adding these inputs. Did you have any idea in mind ?
In fact, there are two needs that we have to address : 
- The user can fine tune and incrementally build its path for a specific 2D / 3D element along its object structure.
- Frontend components are building their own reference_path and are checking for any occurrences in the raw JSONs. So these references needs to be in the JSONs hence, directly computed in the serialization of volmdlr objects.
Without setting these in volmdlr classes, how would you target a mesh on the frontend if it does not bear the reference_path set by the user ?

As for the adoption from the community, that is why I added a default value in it, so that one can absolutely ignore it and it has no impact what so ever on the final outcome. There is absolutely no need to set these reference_pathes

**Comment by GabrielJMS** [comment]
@GhislainJ 

I think this is the easiest way for implementing these functionalities you have mentioned, but not the best one. We should create an application framework for vomldlr, like OCAF is for open cascade, which can also be useful in the future, when others features requests appear 

I took this from the OCAF documentation, it seems to address the same functionalities that we are searching for?

> Developing a design application requires addressing many technical aspects. In particular, given the functional specification of your application, you must at least:
> 
> - Design the architecture of the application— definition of the software components and the way they cooperate;
> - Define the data model able to support the functionality required — a design application operates on data maintained during the whole end-user working session;
> - Structure the software in order to:
> - **synchronize the display with the data — commands modifying objects must update the views;**
> - support generalized undo-redo commands — this feature has to be taken into account very early in the design process;
> - Implement the function for saving the data — if the application has a long life cycle, the compatibility of data between versions of the application has to be addressed;
> - Build the application user interface.

see: https://dev.opencascade.org/doc/overview/html/occt_user_guides__ocaf.html

**Review by GabrielJMS — APPROVED** [review]

**Comment by GhislainJ** [comment]
CI needs #1282 to work properly

**Pull request merged**
