### PR TITLE
points copy hull

### PR DESCRIPTION
**Pull request by MackJoly**
* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bug fix: Method points_convex_hull, concave_hull, convex_hull_points don't gave back the same list of points used in inputs. I added copy of these points at the beginning of each method.
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

### CODE REVIEW

**Review by WirajanDASILVA — APPROVED** [review]
@MackJoly, I believe we should analyse once again both methods for convex hull points (Dessia's and scypy's one, after the changes made by @pgibertini)

**Comment by MackJoly** [comment]
@WirajanDASILVA I agree with you, i think @pgibertini already done changes perhaps it is not necessary

**Comment by WirajanDASILVA** [comment]
> @WirajanDASILVA I agree with you, i think @pgibertini already done changes perhaps it is not necessary

he has fixed the problem when the points were not well ordered for SciPy's based method. I don't if you remember, but if I am correct, that was the main problem for this method, right?

**Comment by MackJoly** [comment]
> > @WirajanDASILVA I agree with you, i think @pgibertini already done changes perhaps it is not necessary
> 
> he has fixed the problem when the points were not well ordered for SciPy's based method. I don't if you remember, but if I am correct, that was the main problem for this method, right?

That's it ! Scipy method didn't gave ordered points. This PR is to create copy before doing a method that impacts points given.

**Review by WirajanDASILVA — APPROVED** [review]

**Pull request merged**
