### PR TITLE
Fix: Arc2D is_trigo in rotation / translation / frame_mapping operations

### PR DESCRIPTION
**Pull request by pgibertini**
* **Please check if the PR fulfills these requirements**
- [x] The commit messages follows our guidelines (explicit, in english)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix: is_trigo attribute was not conserved when performing rotation / translation / frame_mapping operations
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

### CODE REVIEW

**Comment by GabrielJMS** [comment]
We've changed the definition of Circle2D and Frame2D. Now we use a Frame2D in the circle definition. This allows us to easily control the Circle/Arc Orientation. And the Arc2D now always will follows the direction of the Circle2D it was built on, this means it reflects the parameter is_trigo of its circle.

**Comment by GabrielJMS** [comment]
We've changed the definition of Circle2D and Frame2D, now we use a Frame2D in the circle definition. This allows us to easly control the Circle Orientation. And the Arc2D now always will follows the direction of the Circle2D it was built on, this means it reflects the parameter is_trigo of its circle

**Review by GabrielJMS — CHANGES_REQUESTED** [review]
We've changed the definition of Circle2D and Arc2D. Now we use a Frame2D in the circle definition. This allows us to easily control the Circle/Arc Orientation. And the Arc2D now always will follows the direction of the Circle2D it was built on, this means it reflects the parameter is_trigo of its circle. A classmethod from_center_and_radius is kept in Circle2D to allow users to create a Circle2D from a center and a radius

**Comment by pgibertini** [comment]
As Circle definition has change, this PR doesn't solve any bug as it was solve by the Circle2D refactor, but it introduces a small refactor and add some tests.

**Review by GabrielJMS — APPROVED** [review]

**Pull request merged**
