### PR TITLE
Triangle copy

### PR DESCRIPTION
**Pull request by MackJoly**
* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bug fix: triangle._check_platform(), error due to alpha and color not in dict
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

### CODE REVIEW

**Review by AxelRinghausen — APPROVED** [review]

**Comment by AxelRinghausen** [comment]
Merging into `master` on purpose?

**Comment by MackJoly** [comment]
Yes on master because the next release is in 4 weeks and it's important to make the platform work

**Review by masfaraud — CHANGES_REQUESTED** [review]
Triangle inherit from Face, and Face does not handle color & alpha, the shells does.
What is the purpose to put it on faces?

**Comment by MackJoly** [comment]
> Triangle inherit from Face, and Face does not handle color & alpha, the shells does. What is the purpose to put it on faces?

I think I put it back then, I will change it because you're right, it is not really necessary to have color and alpha in Triangle. Furthermore they are stocked in a Shell

**Comment by MackJoly** [comment]
I think the PR is no more available because I found the problem on my side, I close it

**Pull request closed without merging**
